/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BINDIR "/usr/local/bin"

#define BUILD_DRM_COMPOSITOR 1

#define BUILD_FBDEV_COMPOSITOR 1

#define BUILD_HEADLESS_COMPOSITOR 1

#define BUILD_RDP_COMPOSITOR 1

#define BUILD_VAAPI_RECORDER 1

#define BUILD_WAYLAND_COMPOSITOR 1

#define BUILD_X11_COMPOSITOR 1

#define BUILD_XWAYLAND 1

#define DATADIR "/usr/local/share"

#define ENABLE_EGL 1

#define ENABLE_JUNIT_XML 1

#define HAVE_DBUS 1

#define HAVE_DRM_ADDFB2_MODIFIERS 1

#define HAVE_DRM_ATOMIC 1

#define HAVE_DRM_FORMATS_BLOB 1

#define HAVE_FREERDP_VERSION_H 1

#define HAVE_GBM_FD_IMPORT 1

#define HAVE_GBM_MODIFIERS 1

#define HAVE_INITGROUPS 1

#define HAVE_JPEG 1

#define HAVE_LCMS 1

#define HAVE_LIBDRM_INTEL 1

#define HAVE_LINUX_SYNC_FILE_H 1

#define HAVE_MKOSTEMP 1

#define HAVE_PANGO 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_STRCHRNUL 1

#define HAVE_SYSTEMD_LOGIN 1

#define HAVE_SYSTEMD_LOGIN_209 1

#define HAVE_WEBP 1

#define HAVE_XCB_XKB 1

#define HAVE_XKBCOMMON_COMPOSE 1

#define LIBEXECDIR "/usr/local/libexec"

#define LIBWESTON_MODULEDIR "/usr/local/lib/x86_64-linux-gnu/libweston-6"

#define MAJOR_IN_SYSMACROS 1

#define MODULEDIR "/usr/local/lib/x86_64-linux-gnu/weston"

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/wayland/weston/issues/"

#define PACKAGE_STRING "weston 6.0.1"

#define PACKAGE_URL "https://wayland.freedesktop.org"

#define PACKAGE_VERSION "6.0.1"

#define USE_RESIZE_POOL 1

#define VERSION "6.0.1"

#define WESTON_NATIVE_BACKEND "drm-backend.so"

#define WESTON_SHELL_CLIENT "weston-desktop-shell"

#define XSERVER_PATH "/usr/bin/Xwayland"

#define _ALL_SOURCE 1

#define _GNU_SOURCE 1

